name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup npm
      uses: actions/setup-node@v4
      with:
          version: 20

    - name: setup
      run: make dev-setup

    - name: build
      run: make appstore
